-- DROP TABLE IF EXISTS `#__protostore_customer`;
DROP TABLE IF EXISTS `#__protostore_email`;
-- DROP TABLE IF EXISTS `#__protostore_email_log`;
DROP TABLE IF EXISTS `#__protostore_discount`;
DROP TABLE IF EXISTS `#__protostore_currency`;
-- DROP TABLE IF EXISTS `#__protostore_order`;
DROP TABLE IF EXISTS `#__protostore_order_log`;
DROP TABLE IF EXISTS `#__protostore_order_tracking`;
-- DROP TABLE IF EXISTS `#__protostore_customer_address`;
-- DROP TABLE IF EXISTS `#__protostore_order_products`;
-- DROP TABLE IF EXISTS `#__protostore_product`;
DROP TABLE IF EXISTS `#__protostore_coupon_cart`;
DROP TABLE IF EXISTS `#__protostore_option_preset`;
DROP TABLE IF EXISTS `#__protostore_cart_addresses`;
DROP TABLE IF EXISTS `#__protostore_cart`;
DROP TABLE IF EXISTS `#__protostore_cart_item`;
DROP TABLE IF EXISTS `#__protostore_zone`;
DROP TABLE IF EXISTS `#__protostore_country`;
DROP TABLE IF EXISTS `#__protostore_shipping_rate`;
DROP TABLE IF EXISTS `#__protostore_zone_shipping_rate`;
-- DROP TABLE IF EXISTS `#__protostore_product_option`;
-- DROP TABLE IF EXISTS `#__protostore_product_option_values`;
DROP TABLE IF EXISTS `#__protostore_setup`;
